package com.yaa.rpg.playit.persistence.impl;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

import com.yaa.rpg.playit.model.Riddle;
import com.yaa.rpg.playit.persistence.RiddleDao;

public class RiddleDaoImpl implements RiddleDao {

	public RiddleDaoImpl() {
		loadRiddlesMap();
	}


	Map<Integer, Riddle> riddlesCache =new HashMap<>();
 
	
	@Override
	public String getRiddle(int level) {
		Riddle riddle=riddlesCache.get(level);
		return riddle!=null?riddle.getQuestion():"";
	}

	@Override
	public boolean checkRiddleAnswer(String answer, int level) {
		return answer.equalsIgnoreCase(getAnswer(level));
	}

	private String getAnswer(int level) {
		Riddle riddle=riddlesCache.get(level);
		return riddle!=null?riddle.getAnswer():"";
	}

	@Override
	public String getRiddleHint(Integer level) {
		String answer = getAnswer(level);
		StringBuilder hint = new StringBuilder();
		for (int i = 0; i < answer.length(); i++) {
			int seed = i+answer.length();
			if ((((int)Math.random()*100)+seed)%2==0) {
				hint.append(answer.charAt(i)+" ");
			} else {
				hint.append("_ ");
			}
		}
		return hint.toString();
	}
	
	
	private void loadRiddlesMap(){
		riddlesCache=
		Arrays.asList(new Riddle(1, "I get wet when drying. I get dirty when wiping. What am I?","Towel"),
		new Riddle(2, "I can be cracked, made, told, and played. What am I?","Joke"),
		new Riddle(3, "I wiggled and cannot see, sometimes underground and sometimes on a tree. I really don’t want to be on a hook, and I become a person when combined with a book?","Worm"),
		new Riddle(4, "I like to twirl my body but keep my head up high. After I go in, everything becomes tight. What am I?","Screw"),
		new Riddle(5, "I am gentle enough to soothe your skin, light enough to fly in the sky, strong enough to crack rocks. What am I?","Water"),
		new Riddle(6, "I can fly but have no wings. I can cry but I have no eyes. Wherever I go, darkness follows me. What am I?","Cloud"),
		new Riddle(7, "Although I may have eyes I cannot see. I have a round brown face with lots of acne. What am I?","Potato"),
		new Riddle(8, "I eat, I live. I breathe, I live. I drink, I die. What am I?","Fire"),
		new Riddle(9, "I am a seed with three letters in my name. Take away the last two and I still sound the same. What am I?","Pea"),
		new Riddle(10, "I am lighter than air but a hundred people cannot lift me. Careful, I am fragile. What am I?","Bubble"),
		new Riddle(11, "Although glory but not at my best. Power will fall to me finally, when the man made me is dead. What am I?","Prince"),
		new Riddle(12, "I am the type of room you can not enter or leave. Raise from the ground below, I could be poisonous or a delicious trea. What am I?","Mushroom"),
		new Riddle(13, "The more you take of me, the more you leave behind. What am I?","Footstep"),
		new Riddle(14, "I go up and never come down no matter how hard you wish. As I get higher, more wrinkles crawl on to the face. What am I?","Age"),
		new Riddle(15, "I can be long or short. I can be grown or bought. I can be painted or left bare. My tip can be round or square. (one word) What am I?","Fingernails"),
		new Riddle(16, "I have a neck and no head, two arms but no hands. I’m with you to school, I’m with you to work. What am I?","Shirt"),
		new Riddle(17, "I shrink smaller every time I take a bath. What am I?","Soap"),
		new Riddle(18, "I am heavy forward, but backward I’m not. What am I?","Ton"),
		new Riddle(19, "I wear a green jacket on the outside, white jacket as a second layer, and a red jacket inside. I am pregnant with a lot of babies. What am I?","Watermelon"),
		new Riddle(20, "I am good at concealing what’s real and hide what’s true. Sometime, I bring out the courage in you! What am I?","Makeup"),
		new Riddle(21, "I have a face but no eyes, hands but no arms. What am I?","Clock"),
		new Riddle(22, "With three eyes and a black as night, I frequently knock down ten men with a single strike! What am I?","Bowling ball"),
		new Riddle(23, "I’m grown from darkness but shine with a pale light. Very round I am, and always a lady’s delight. What am I?","Pearl"),
		new Riddle(24, "I am owned by every man, through my length differs. Their wives use me after getting married. What am I?","Lastname"),
		new Riddle(25, "I’m white, perfect for cutting and grinding. For most animals I am a useful tool. What am I?","Teeth"),
		new Riddle(26, "I am always around you but often forgotten. I am pure and clean most time, but occasionally rotten. What am I?","Air"),
		new Riddle(27, "I am that only thing place today before yesterday. (one word) What am I?","Dictionary"),
		new Riddle(28, "I may only be given but never bought. Sinners seek me but saints do not. (one word) What am I?","Forgiveness"),
		new Riddle(29, "I will disappear every time you say my name. What am I?","Silence"),
		new Riddle(30, "I have two bodies joined together as one. When standing still, I ran and ran. What am I?","Hourglass"),
		new Riddle(31, "The more you take away from me, the bigger I shall get. What am I?","Hole"),
		new Riddle(32, "I jump when I walk and sit when I stand. What am I?","Kangaroo"),
		new Riddle(33, "I have fangs and enjoy piercing holes with a single bite. What am I?","Stapler"),
		new Riddle(34, "I have three eyes and only one leg. Obey me or you will be sorry. What am I?","Traffic Light"),
		new Riddle(35, "I have a straight back and sharp teeth to cut objects. What am I?","Saw"),
		new Riddle(36, "You can catch me but cannot throw me. What am I?","Cold"),
		new Riddle(37, "Taken from a mine and then locked up in a wooden case. Never released but used by students everyday. What am I?","Lead"),
		new Riddle(38, "I can never be stolen from you. I am owned by everyone. Some have more, some have less. What am I?","Knowledge"),
		new Riddle(39, "I am a mother from a family of eight. Spins around all day despite my weight. Had a ninth sibling before founding out its fake. What am I?","Earth"),
		new Riddle(40, "The more you have me the less you see. Shine a light on me and I flea. What am I?","Darkness"),
		new Riddle(41, "I turn everything around, but I cannot move. When you see me you see you! What am I?","Mirror"),
		new Riddle(42, "Tear me off and scratch my head, what once red is now black. What am I?","Match"),
		new Riddle(43, "I dance on one feet and knows only one shape. Someone with same name as me is very good with directions. What am I?","Compass"),
		new Riddle(44, "Whoever made me don’t want me; Whoever bought me don’t need me. Whoever use me don’t know me. What am I?","Coffin"),
		new Riddle(45, "When you take away the whole from me, there is always some left. What am I?","Wholesome"),
		new Riddle(46, "I am a word. I become longer when the third letter is removed. What am I?","Lounger"),
		new Riddle(47, "Born in the ocean and white as snow. When I fall back to water I disappear without a trace. What am I?","Salt"),
		new Riddle(48, "As a state in America. I am round on both sides and high in the middle. What am I?","Ohio"),
		new Riddle(49, "I am enjoyed by some, despised by others. Some take me for granted, some treasure me like a gift. I last forever, unless you break me first. What am I?","Marriage"),
		new Riddle(50, "I am a king who’s good at measuring stuff. What am I?","Ruler"),
		new Riddle(51, "I can wave my hands at you, but I never say goodbye. You are always cool when with me, even more so when I am high! What am I?","Electric Fan"),
		new Riddle(52, "I start with “T”, ends with “T”, and within me is “T”. What am I?","Teapot"),
		new Riddle(53, "My first half means container. Not a lot of people understand my language. What am I?","Binary"),
		new Riddle(54, "I walk on 4 legs in the morning, 2 legs at noon, and 3 legs at night. What am I?","Human"),
		new Riddle(55, "I start with an E, end with an E, and have a letter in me. What am I?","Envelope"),
		new Riddle(56, "If a man carries my burden, they will get crushed to death. Though not rich, I leave silver in my track. What am I?","Snail"),
		new Riddle(57, "I have feathers that help me fly; with head and body but I’m not alive. Very skinny and a fixed length, how far I go depends on.What am I?","Arrow"),
		new Riddle(58, "You heard me before, and then again. Afterward I die, until you call me again. What am I?","Echo"),
		new Riddle(59, "I am free the first time and second time, but the third time is going to cost you money. What am I?","Teeth"),
		new Riddle(60, "I always run but never walk, often murmur but never talk, have a bed but never sleep, has a mouth but never eat. What am I?","River"),
		new Riddle(61, "Lighter than feather and softer than silk, yet the strongest man in the world cannot hold me for more than a few minutes. What am I?","Breath"),
		new Riddle(62, "I am the place to turn when nature calls. What am I?","Bathroom"),
		new Riddle(63, "Soft, hairy, from door to door. I am the pet that always stays on the floor. What am I?","Carpet"),
		new Riddle(64, "I am quick when I’m thin. I am slow when I’m fat. Wind is my worst nightmare. What am I?","Candle"),
		new Riddle(65, "I go in dry and come out wet. The longer I stay in, the stronger my surroundings get. What am I?","Tea Bag"),
		new Riddle(66, "If you have me, you want to share me. Once you share me, you won’t have me. What am I?","Secret"),
		new Riddle(67, "I have a head, tail, but no arms and legs. What am I?","Coin"),
		new Riddle(68, "I am full of holes but still holds water. What am I?","Sponge"),
		new Riddle(69, "I sit in a corner while traveling around the world. What am I?","Stamp"),
		new Riddle(70, "I can run but not walk. Wherever I go, thought follows close behind. What am I?","Nose"),
		new Riddle(71, "People need me yet they give me away every day. What am I?","Money"),
		new Riddle(72, "I make a loud noise when changing jacket, becomes bigger and delicious. What am I?","Popcorn"),
		new Riddle(73, "I am owned by the poor, the rich does not need me. If you eat me, you will die! What am I?","Nothing"),
		new Riddle(74, "You do not want me when you don’t have me, but when you have me you don’t want to lose me.","Lawsuit"),
		new Riddle(75, "With a halo of water and a tongue of wood, stone as skin long I stood. What am I?","Castle"),
		new Riddle(76, "I am a kind of coat that can only be put on when wet. What am I?","Paint"),
		new Riddle(77, "I have a ring but no fingers. I used to stay still all the time, but nowadays I follow you around. What am I?","Telephone"),
		new Riddle(78, "I begin and have no end. Eventually I will be the ending of all that has begun. What am I?","Death"),
		new Riddle(79, "I must be broken before you can use me. What am I?","Egg"),
		new Riddle(80, "I stink in living but when dead smells good. What am I?","Pig"),
		new Riddle(81, "My rings are not worth much, but they do tell my age. What am I?","Tree"),
		new Riddle(82, "I climb higher as I get hotter. I can never escape from my crystal cage. What am I?","Mercury"),
		new Riddle(83, "What force and strength cannot get through, I with my unique teeth can do. What am I?","Key"),
		new Riddle(84, "I am pronounced as one letter, written with three. I come in blue, black, brown, or grey. Reverse me and I read the same either way. What am I?","Eye"),
		new Riddle(85, "Kings and queens may cling to power, and the jesters may have their call. I am the most common but I can rule them all. What am I?","Ace"),
		new Riddle(86, "I take off my clothes when you put on your clothes. I put on my clothes when you take off your clothes. What am I?","Clothes Hanger"),
		new Riddle(87, "I may be made of metal, bone, or wood and have many teeth. My bite hurts no one and the ladies love me. What am I?","Comb"),
		new Riddle(88, "I am not a toy, though many use me for pleasure. I have a butt, but I cannot poop. What am I?","Cigarette"),
		new Riddle(89, "I can’t go left, I can’t go right. I am forever stuck in a building over three stories high. What am I?","Elevator"),
		new Riddle(90, "I go up when the rain comes down. What am I?","Umbrella"),
		new Riddle(91, "If you lose me you may cause people around me to lose me too. What am I?","Temper"),
		new Riddle(92, "I beam, I shine, I sparkle white. I’ll brighten the day with a single light. I’ll charm and enchant all. I’ll bring the best in you all. What am I?","Smile"),
		new Riddle(93, "I am a mountain at night, meadow at day. What am I?","Bed"),
		new Riddle(94, "I am an instrument capable of making numerous sound but cannot be touched or seen. What am I?","Voice"),
		new Riddle(95, "Cloud is my mother, wind is my father. What am I?","Rain"),
		new Riddle(96, "I am black, white, and read all over. What am I?","Newspaper"),
		new Riddle(97, "I run around the streets all day. Under the bed or by the door I sit at night, never alone. My tongue hangs out, waiting to be fed during the day. What am I?","Shoe"),
		new Riddle(98, "I am constantly overlooked by everyone but everyone has me. What am I?","Nose"),
		new Riddle(99, "I widen my jaws when you poke two fingers in me. I especially like to devour papers. What am I?","Scissors"),
		new Riddle(100, "I live above a star who never burns. I have 11 neighbors but they never turn. My initial are p, q, r, and sometimes s. What am I?","Seven"),
		new Riddle(101, "I have no voice but I can teach you all there is to know. I have spines and hinges but I am not a door. Once I’ve told you all, I cannot tell you more. What am I?","Book"),
		new Riddle(102, "I always have to work with something in my eye. What am I?","Needle"),
		new Riddle(103, "I am bought by the yard but worn by the foot. What am I?","Carpet"),
		new Riddle(104, "I never was but always will be. No one ever saw me but everyone knows I exist. I give people the motivation to better themselves everyday. What am I?","Tomorrow"),
		new Riddle(105, "I go up and down at the same time. Up towards to sky and down towards the ground. What am I?","See-saw"),
		new Riddle(106, "I am a sharp looking horse with a flaxen tail. The longer I run the shorter my tail becomes. What am I?","Needle"),
		new Riddle(107, "I come in different colors and shapes. Some parts of me are curvy, some are straight. You can put me anywhere you like, but there is only one right place for me. What am I?","Jigsaw Puzzle"),
		new Riddle(108, "I am alive without breath and cold as death. I am never thirsty but always drinking. What am I?","Fish"),
		new Riddle(109, "I belong to you but others use me more often than you do. What am I?","Name"),
		new Riddle(110, "I am rarely touched but often held, and if you are smart you’ll use me well. What am I?","Tongue"),
		new Riddle(111, "I go around and in the house, but never touches the house. What am I?","Sun"),
		new Riddle(112, "I am a protector. I sit on a bridge. One person can see right through me, while others wonder what I hide. What am I?","Sunglasses"),
		new Riddle(113, "I fly away as soon as you set me loose. People around you may slowly move away once they sense my presence. What am I?","Fart"),
		new Riddle(114, "I am an insect, half of my name is another insect. I am similar to the name of a famous band. What am I?","Beetle"),
		new Riddle(115, "A necessity to some, a treasure to many, I’m best enjoyed among pleasant company. Some like me hot, some like me cold. Some prefer mild, some like me bold. What am I?","Coffee"),
		new Riddle(116, "You cannot keep me until you have given me. What am I?","Your Word"),
		new Riddle(117, "I go from house to house, a messenger small and tight. Weather it rains or snows. I sleep outside at night. What am I?","Road"),
		new Riddle(118, "I’m really blue, but when you see me I’m red. You don’t see me too often. I’m there for you if you’re hurt, but I’m good for you. What am I?","Blood"),
		new Riddle(119, "I am a time for gathering crops. Remove the first three letters I become an object you can wear. What am I?","Harvest"),
		new Riddle(120, "I hold two people together but touch only one. What am I?","Wedding Ring"),
		new Riddle(121, "You turn me over after you have traveled far. What am I?","Odometer"),
		new Riddle(122, "Break me but I’ll continue to work, touch me and maybe I’ll stay with you forever. What am I?","Heart"),
		new Riddle(123, "I won’t break if you throw me off from the highest building but I will break if you place me in the ocean. What am I?","Tissue"),
		new Riddle(124, "I hide in a dark tunnel awaiting my time. I can only be released by pulling back. Once released, I may do unstoppable damage. What am I?","Bullet"),
		new Riddle(125, "I have cities with no people, forests with no trees, and oceans with no water. What am I?","Map"),
		new Riddle(126, "I am a nut with a hole. What am I?","Donut"),
		new Riddle(127, "When it comes to me, you go on red and stops on green. What am I?","Watermelon"),
		new Riddle(128, "Physicists have built devices to move me very fast. My last seven letters can be commonly found in newspapers, magazines, and journals. What am I?","Particles"),
		new Riddle(129, "I can the same written do forward, backward, and upside down. What am I?","Noon"),
		new Riddle(130, "I sleep when you are awake, I am awake when you fall asleep. I can fly but no feathers to aid my flight. What am I?","Bat"),
		new Riddle(131, "I only exist when you are here. Where you never were, I can never be. What am I?","Reflection"),
		new Riddle(132, "I can be red, blue, purple, and green. No one can reach me, not even the queen. What am I?","Rainbow"),
		new Riddle(133, "I have six faces but not even one body connected, 21 eyes in total but cannot see. What am I?","Dice"),
		new Riddle(134, "I have a head and a tail but my eyes can never see my tail. What am I?","Coin"),
		new Riddle(135, "You hold my tail while I fish for you. What am I?","Net"),
		new Riddle(136, "I am a box who holds keys but not locks. With the right combination I may unlock your soul. What am I?","Piano"),
		new Riddle(137, "I come without being fetched at night, hides away as soon as daylight strikes. Although I may look small, I am much mightier than what you can imagine. What am I?","Star"),
		new Riddle(138, "I do not contain flesh, feather, or scales; yet I have fingers and thumbs. What am I?","Glove"),
		new Riddle(139, "I am all around you, but you cannot see me. I have no throat, but you can hear me. Valued during summer but despised in the winter. What am I?","Wind"),
		new Riddle(140, "I cannot be burned in fire or drowned in water. What am I?","Ice"),
		new Riddle(141, "I contain six letters, minus one and you got twelve. What am I?","Dozens"),
		new Riddle(142, "Sometimes I fly as fast as the speed of light. Sometime I crawl as slow as a snail. Unknown until I am measured but you will certainly miss me when I’m gone. What am I?","Time"),
		new Riddle(143, "I spend most of my day eating white. When I am quick enough, I get rewarded with fruit and somethings blue. In a dark room with blue walls, I run from the ghost that roam the halls. What am I?","Pac-man"),
		new Riddle(144, "I have roots nobody sees. I am taller than trees. Up, up I go but I never grow. What am I?","Mountain"),
		new Riddle(145, "I am a ship that can be made to ride the greatest waves. I am not built by objects, but built by minds. What am I?","Friendship"),
		new Riddle(146, "I have a mouth on my head and eat everything. What am I?","Backpack"),
		new Riddle(147, "I do not have eyes but I once could see. I used to have thoughts but now I’m empty. What am I?","Skull"),
		new Riddle(148, "I get paid to shoot people, then blow them up. What am I?","Photographer"),
		new Riddle(149, "I can be the book one can never finish reading. What am I?","Autobiography"),
		new Riddle(150, "I am lighter than the material I am made of. You see parts of me but more of me is hidden underneath. What am I?","Iceberg"),
		new Riddle(151, "I was not born, but I am here. I have no name, but I am given many. I was made by science and life. What am I?","Clone"),
		new Riddle(152, "I hold two meanings. With one I may be broken, with the other I hold on. What am I?","Tie"),
		new Riddle(153, "I love to twist and dance. Though wingless, I fly high up into the sky. What am I?","Kite"),
		new Riddle(154, "You throw away my outside, you cook my inside. Then you eat my outside and you throw away my inside. What am I?","Corn"),
		new Riddle(155, "I am a rock group with four members. All dead, one was assassinated. What am I?","Mt. Rushmore"),
		new Riddle(156, "I go in hard, come out soft. Blow me hard and I’ll make a pop. What am I?","Gum"),
		new Riddle(157, "I am a food with 5 letters. If you remove the first letter I am a form of energy. Remove two and I’m needed to live. Scramble the last 3 and you can drink me down. What am I?","Wheat"),
		new Riddle(158, "I have a hundred legs, but cannot stand. I have a long neck, but no head. I cannot see, and I help keep your house neat and tidy. What am I?","Broom"),
		new Riddle(159, "I cannot be bought, cannot be sold, even if I’m sometimes made of gold. What am I?","Heart"),
		new Riddle(160, "I can be found after you remove 6 letters from BSAINXLEATEARS. What am I?","Banana"),
		new Riddle(161, "I run up and down the stairs without moving. What am I?","Rug"),
		new Riddle(162, "When I point up, it’s bright. When I point down, it’s dark. What am I?","Light Switch"),
		new Riddle(163, "I ask no questions but receive a lot of answers. What am I?","Doorbell"),
		new Riddle(164, "You use a knife to slice my head and weep beside me when I am dead. What am I?","Onion"),
		new Riddle(165, "I am a fruit with seed on the outside. What am I?","Strawberry"),
		new Riddle(166, "I belong to everyone. Sometimes make you happy, sometimes make you sad. I will never end until the day you do. What am I?","Thoughts"),
		new Riddle(167, "I can wake you up in the morning but I require no electricity or winding. What am I?","Rooster"),
		new Riddle(168, "I can generate fear and some say I come out of your ears. I am as quite as a mouse but not welcomed in the house. What am I?","Smoke"),
		new Riddle(169, "You throw me out when you use me and take me in when you are done. What am I?","Anchor"),
		new Riddle(170, "I drift forever with the current and flows to your everyday life. I make living easy but I am good at killing people too. What am I?","Electricity"),
		new Riddle(171, "I have 24 keys but cannot open any locks. Sometimes loud, sometimes soft. What am I?","Music"),
		new Riddle(172, "I am clean when I’m black, dirty when I’m white. What am I?","Chalkboard"),
		new Riddle(173, "My first two letters say my name. My last letter asks a question. What I embrace I destroy. What am I?","Ivy"),
		new Riddle(174, "I have wheels and flies, yet I am not an aircraft. What am I?","Garbage Truck"),
		new Riddle(175, "I have three heads. Cut off one, I become stronger. Cut off two, I become ten. What am I?","Fox"),
		new Riddle(176, "I contain five little items of an everyday sort. You can find all five in a tennis court. What am I?","Vowels"),
		new Riddle(177, "I am black when you buy me, red when you use me, when I turn white. You know it’s time to throw me away. What am I?","Charcoal"),
		new Riddle(178, "I can sizzle like bacon. I am made with an egg, I have plenty of backbone, but lack a good leg. I peel layers like onions, but still remain whole. I can be long, like a flagpole, yet fit in a hole. What am I?","Snake"),
		new Riddle(179, "I can swim but never get wet. I can run but never get tired. I follow you everywhere but never say a word. What am I?","Shadow"),
		new Riddle(180, "I am the beginning of the end, and the end of time and space. I am essential to creation, and I surround every place. What am I?","E"),
		new Riddle(181, "You can throw me away, but I will always be coming back. What am I?","Boomerang"),
		new Riddle(182, "I am in the past, never in the future. I don’t exist, but have existed. I saw what you saw, and this is what I will ever see. What am I?","Memory"),
		new Riddle(183, "In prison I will be found, But I’ll never be in court, Unless there’s more than one. What am I?","S"),
		new Riddle(184, "I’ve been argued on my colour. Without me you’ll die. So many attempts on your life use me, so make sure you have many of my “White” friends. What am I?","Red Blood Cell"),
		new Riddle(185, "I see what you see, feel what you feel, and hear what you hear. I know all of your moves before you make them. I even know the moves you didn’t make. What am I?","Brain"),
		new Riddle(186, "I am flora, not fauna. I am foliage, not trees. I am shrubbery, not grass. What am I?","Bush"),
		new Riddle(187, "I come off a beautiful creature, which soars in the sky. I come off a peckish creature, which has a tail as mighty as the sun! I am sometimes dirty, and parents beg you not to pick me up. What am I?","Feather"),
		new Riddle(188, "I am easy to waste and unstoppable What am I?","Time"),
		new Riddle(189, "I am not very commonly found! Only in some rainforest! I have an odd number of toes! I’m very lazy and hang upside down! What am I?","Sloth"),
		new Riddle(190, "I am one small little piece of paper, yet sometimes hold lots of value. I am all you need to get in to big events, but will cost you. I am an important part of travel. And if lost, you’re not coming. What am I?","Ticket"),
		new Riddle(191, "A hole in a pole. Though I fill a hole in white, I’m used more b the day and less by the night. What am I?","Eye"),
		new Riddle(192, "I start new then become old. Start clean but be one dirty. I usually start big then become little. What am I?","Shoes"),
		new Riddle(193, "I can fall off a building and live, but in water I will die. What am I?","Paper"),
		new Riddle(194, "I am what bring things together. Without me everything you see would be a total mass or debris everywhere. What am I?","Gravity"),
		new Riddle(195, "I have been the beginning of ideas for all time, yet I am just one simple small object, the things that you can use me for can be frustrating and also I can be pretty. I have some of the most valuable thing in the world on me, yet almost everyone owns me. With me you can make anything. What am I?","Paper"),
		new Riddle(196, "The thunder comes before the lightning, and the lightning comes before the cloud, The rain dries all the land it touches, wrapping the earth in a blood red shroud. What am I?","Volcano"),
		new Riddle(197, "I have palms but not on hands, I offer foods from distant lands, When at my peak you’ll see me smoke, I’m famous for my friendly folk, My flowers grow and yet they lay, There’s fire where a man will play. What am I?","Hawaii"),
		new Riddle(198, "I am beautiful, up in the sky. I am magical, yet I cannot fly. To people I bring luck, to some people, riches. The boy at my end does whatever he wishes. What am I?","Rainbow"),
		new Riddle(199, "I may seem real but it always turns out I was never there in the first place… you only see me during a certain resting stage. What am I?","Dream"),
		new Riddle(200, "The 8 of us go forth and back to protect our king from a foes attack. What am I?","Pawns"),
		new Riddle(251, "I give people a huge fright, but at the end I’m sweet. I normally celebrate at night, when there’s less heat. What am I?","Halloween"),
		new Riddle(252, "I am the ultimate killing machine, used not once but TWICE, I can be made by humans. What am I?","War"),
		new Riddle(253, "In my life I must bare, my bloodline I must share. What am I?","Sibling"),
		new Riddle(254, "Two in a whole and four in a pair. Six in a trio you see. Eight’s a quartet but what you must get is the name that fits just one of me. What am I?","Half"),
		new Riddle(255, "I twist and turn and leaves a loop. What am I?","Shoelace"),
		new Riddle(256, "I am easy to see, but no one likes looking at me. Without me, there would be no you. I can make you complain, or make you happy. But you almost always take me for granted. What am I?","Sun"),
		new Riddle(257, "I am a type of cheese made backwards. What am I?","Edam"),
		new Riddle(258, "Though I am dark, Adam married me. What am I?","Eve"),
		new Riddle(259, "I am always in front of you, but you will never see me. What am I?","Future"),
		new Riddle(260, "I will go within you, and destroy you. Only because you wanted me too. What am I?","Drugs"),
		new Riddle(261, "I dig out tiny caves, and store gold and silver in them. I also build bridges of silver and make crowns of gold. Sooner or later everybody needs my help, yet many people afraid to let me help them. What am I?","Dentist"),
		new Riddle(262, "To cross the water I’m the way. For water I’m above I touch it not, and truth to say, I neither swim nor move. What am I?","Bridge"),
		new Riddle(263, "I can be simple or I can be complex. I can be found in this riddle or in everyday life. I can be shapes or even colors. What am I?","Pattern"),
		new Riddle(264, "I am edible, pink, and a great summer food. What am I?","Peach"),
		new Riddle(265, "I crushed on Wendy Darling. What am I?","Peter Pan"),
		new Riddle(266, "I am a protector of the scoreboard. What am I?","Goalie"),
		new Riddle(267, "I am needed for most animals and hardcover books. What am I?","Spine"),
		new Riddle(268, "You used to come to me for all sorts of information and knowledge before internet was born. What am I?","Library"),
		new Riddle(269, "I tell people to be careful when handling boxes. What am I?","Fragile"),
		new Riddle(270, "We applaud if you perform well. What am I?","Audience"),
		new Riddle(271, "I look like a tiny trombone. What am I?","Paperclip"),
		new Riddle(272, "I increase head turning rate tremendously for girls at beaches. What am I?","Bikini"),
		new Riddle(273, "I describe a toilet cleaner as well as one of Santa’s reindeer. What am I?","Comet"),
		new Riddle(274, "I can only be played on a windy day. What am I?","Kite"),
		new Riddle(275, "I am a candy that looks like a shepherd’s staff. What am I?","Candy Cane"),
		new Riddle(276, "I begin your sentences. What am I?","Capital"),
		new Riddle(277, "I am a shiny metal sheet that covers BBQ food. What am I?","Aluminum"),
		new Riddle(278, "Deposit red liquid in me. What am I?","Blood Bank"),
		new Riddle(279, "I don’t forget! What am I?","Elephant"),
		new Riddle(280, "Things here are usually tagged with red stickers. What am I ?","Clearance"),
		new Riddle(281, "I am a small paradise surrounded by dryness and heat. What am I?","Oasis"),
		new Riddle(282, "I am a type of weapon for SCI-FI characters. What am I?","Laser"),
		new Riddle(283, "Keep doing me to avoid lens dryness. What am I?","Blink"),
		new Riddle(284, "I flow from the mouth of Homer when he sees doughnuts. What am I?","Drool"),
		new Riddle(285, "I am the noise Santa’s reindeers make. What am I?","Jingle"),
		new Riddle(286, "I store fire-breathing animals. What am I?","Dungeon"),
		new Riddle(287, "Some people avoid me, some people count me, some people just consume me. What am I?","Calories"),
		new Riddle(288, "I am a beverage named after a stick. What am I?","Club Soda"),
		new Riddle(289, "Angels and pilots work with me. What am I?","Wings"),
		new Riddle(290, "I am like thunder in your cranium. What am I?","Headache"),
		new Riddle(291, "Better touch me before you proceed to second. What am I?","First Base"),
		new Riddle(292, "I encourage people to run home and steal. What am I?","Baseball"),
		new Riddle(293, "I am enjoyed with a pot and some pointy sticks. What am I?","Fondue"),
		new Riddle(294, "I am a tool for fairies. What am I?","Magic Wand"),
		new Riddle(295, "I hop around and deliver eggs at Easter. What am I?","Bunny"),
		new Riddle(296, "I am a daily ritual involving using a metal tool on the body. What am I?","Shave"),
		new Riddle(297, "I am the second L in LOL. What am I?","Loud"),
		new Riddle(298, "I am a delicious way of representing data. What am I?","Pie Chart"),
		new Riddle(299, "My flavors ranges from strawberry to toe. What am I?","Jam"),
		new Riddle(300, "I am known for my natural tuxedo and marching. What am I ?","Penguin"),
		new Riddle(301, "A popular afterlife location to send evil people. What am I?","Hell"),
		new Riddle(302, "I am a desire to munch. What am I?","Hunger"),
		new Riddle(303, "I keep things green and keep kids happy during summer time. What am I?","Sprinkler"),
		new Riddle(304, "Canine children. What am I?","Puppy"),
		new Riddle(305, "I am a way to say goodbye to your sweetheart. What am I?","Kiss"),
		new Riddle(306, "I love spinach. What am I?","Popeye"),
		new Riddle(307, "I have strong affection for belly buttons. What am I?","Lint"),
		new Riddle(308, "I am a sound made by felines when petted. What am I?","Purr"),
		new Riddle(309, "I am so delicious that I require a house to contain me. What am I?","Pancakes"),
		new Riddle(310, "Cats and deflation tires make this noise. What am I?","Hiss"),
		new Riddle(311, "I am a activity dogs are very good at when a ball is thrown. What am I?","Fetch"),
		new Riddle(312, "I am very afraid of doing scary activities. What am I?","Chicken"),
		new Riddle(313, "Found at the back of the book. What am I?","Appendix"),
		new Riddle(314, "Hide me from your parents if you have done bad academically this year. What am I?","Report Card"),
		new Riddle(315, "I mean goodbye for South Americans. What am I?","Adios"),
		new Riddle(316, "I am longer than a decade and shorter than a millennium. What am I?","Century"),
		new Riddle(317, "I help you carry your books. What am I?","Backpack"),
		new Riddle(318, "You need thousands of me to create a digital image. What am I?","Pixel"),
		new Riddle(319, "The Titanic is still here. What am I?","Atlantic"),
		new Riddle(320, "I am often sold by children entrepreneurs in summer time. What am I?","Lemonade"),
		new Riddle(321, "I am milky white and scares people. What am I?","Ghost"),
		new Riddle(322, "Send poorly behaved children to me and let them sit here. What am I?","Corner"),
		new Riddle(323, "I am a creature with a “tight” name. What am I?","Seal"),
		new Riddle(324, "Four leaves I have. What am I?","Shamrock"),
		new Riddle(325, "I am the most famous dinner. What am I?","Last Supper"),
		new Riddle(326, "I was cracked by Indiana Jones. What am I?","Whip"),
		new Riddle(327, "I am sometimes referred to as chips. What am I?","French Fries"),
		new Riddle(328, "Teenage girls are pros at creating me. Learn me in classes. What am I?","Drama"),
		new Riddle(329, "I am million people’s wakeup call. What am I?","Coffee Bean"),
		new Riddle(330, "My teeth help me suck. What am I?","Vampire"),
		new Riddle(331, "Island hello. What am I?","Hello"),
		new Riddle(332, "I help boats park. What am I?","Anchor"),
		new Riddle(333, "Santa shakes his belly like me. What am I?","Jelly"),
		new Riddle(334, "I suck. What am I?","Vaccuum"),
		new Riddle(335, "I am the kind of food monkey likes, and people slip on me and fall in cartoons. What am I?","Banana"),
		new Riddle(336, "I carry you down a gental stream. What am I?","Rowboat"),
		new Riddle(337, "I invade your home once a year… but only if you’ve been good. What am I?","Santa Claus"),
		new Riddle(338, "I am a type of animal that hang out in the mist. What am I?","Gorilla"),
		new Riddle(339, "An action done on mosquito bites. What am I?","Scratch"),
		new Riddle(340, "The time between daylight and darkness when blood drinkers like to come out. What am I?","Twilight"),
		new Riddle(341, "A piece of paper that takes most people 3 or 4 years to get. What am I?","Diploma"),
		new Riddle(342, "I am used when you jump off a bridge for fun. What am I?","Bungee"),
		new Riddle(343, "I am pinched by grandmas. What am I?","Cheeks"),
		new Riddle(344, "I mirror your actions. What am I?","Copycat"),
		new Riddle(345, "I am a busy worker who is a water mammal. What am I?","Beaver"),
		new Riddle(346, "I am ten little beans your look at everyday. What am I?","Toes"),
		new Riddle(347, "I travel in a gaggle. What am I?","Goose"),
		new Riddle(348, "Light me up in backyard gatherings. What am I?","Charcoal"),
		new Riddle(349, "I save lives on the ground and in the air. What am I?","Seatbelt"),
		new Riddle(350, "I destroy your home from inside out. What am I?","Termite"),
		new Riddle(351, "The only amusing part of the body. What am I?","you are"),
		new Riddle(352, "I am the home for feathery animals. What am I?","Nest"),
		new Riddle(353, "I am the state when a person is holding a person inside. What am I?","Pregnant"),
		new Riddle(354, "When you are inside me, you will be encouraged to slam other cars. What am I?","Bumper Car"),
		new Riddle(355, "I am a living following the wealthy and beautiful. What am I?","Paparazzi"),
		new Riddle(356, "I am expelled from you orally with a sound. What am I?","Burp"),
		new Riddle(357, "Find me on body builders or in the drink aisle. What am I?","Six Pack"),
		new Riddle(358, "I am the best thing that can happen after a stick hits a ball. What am I?","Home Run"),
		new Riddle(359, "I stink up your breath and fights evil vampires. What am I?","Garlic"),
		new Riddle(360, "I am commonly abbreviated to H. What am I?","Hydrogen"),
		new Riddle(361, "I am the minerals vital for your good health. What am I?","Vitamin"),
		new Riddle(362, "I am owned by Old McDonald. What am I?","Farm"),
		new Riddle(363, "I shared by goats, devils, and unicorns. What am I?","Horn"),
		new Riddle(364, "I let water fall on you while everyone else stays dry. What am I?","Shower"),
		new Riddle(365, "I am a caribbean shape that makes ships disappear. What am I?","Triangle"),
		new Riddle(366, "Rub me and a genie might appear. What am I?","Lamp"),
		new Riddle(367, "Makeup for finger tips. What am I?","Nail Polish"),
		new Riddle(368, "I direct you from outer space. What am I?","GPS"),
		new Riddle(369, "I transfer oxygen from the atmosphere to your blood. What am I?","Lungs"),
		new Riddle(370, "I am the reaction after enjoying soda. What am I?","Belch"),
		new Riddle(371, "Use me to reward good behavior. What am I?","Treat"),
		new Riddle(372, "I cause involuntary movements in your vehicle. What am I?","Tow Truck"),
		new Riddle(373, "I am a person who pretends to be someone else. What am I?","Imposter"),
		new Riddle(374, "I am a lunch money thief. What am I?","Bully"),
		new Riddle(375, "Although it sounds like I work on a transportation device, I actually work in a restaurant. What am I?","Busboy"),
		new Riddle(376, "A move made popular b the King of Pop. What am I?","Moon Walk"),
		new Riddle(377, "Use me if you really want to see inside someone. What am I?","X-ray"),
		new Riddle(378, "I am a mini solar powered computer. What am I?","Calculator"),
		new Riddle(379, "I can be entertaining until you realize some pieces have been lost. What am I?","Puzzle"),
		new Riddle(380, "I am an activity involving pins flying int eh air. What am I?","Juggling"),
		new Riddle(381, "Turkey day. What am I?","Thanksgiving"),
		new Riddle(382, "There are four of us, but it seems like everyone loves spades the most. What am I?","Aces"),
		new Riddle(383, "I am a shower that lights up the sky. What am I?","Meteor"),
		new Riddle(384, "I carried by mad animals. What am I?","Rabies"),
		new Riddle(385, "I am nature’s way of applauding lightning. What am I?","Thunder"),
		new Riddle(386, "A large oasis in the desert. Come with cash and leave with none. What am I?","Las Vegas"),
		new Riddle(387, "Sing me to a baby about to go to sleep. What am I?","Lullaby"),
		new Riddle(388, "Digital white-out. What am I?","Delete"),
		new Riddle(389, "3 point goal. What am I?","Field Goal"),
		new Riddle(390, "I can be heard in a court of carried with you. What am I?","Case"),
		new Riddle(391, "Score in end zones. What am I?","Touchdown"),
		new Riddle(392, "I am rubber you can eat! What am I?","Jelly"),
		new Riddle(393, "Skirts for men. What am I?","Kilt"),
		new Riddle(394, "I help engines spin and pants stay up. What am I?","Belt"),
		new Riddle(395, "I produce wool and spit a lot. What am I?","Llama")).stream().collect(Collectors.toMap(Riddle::getDifficulty, Function.identity())) ;
	}
	
	

}
